<section class="faq-one" id="slider9">
    <div class="faq-one_bg" style="background-image:url({{ asset('images/background/faq-bg.png') }})">
    </div>
    <div class="faq-one_icon" style="background-image:url({{ asset('images/icons/step.png') }})"></div>
    <div class="auto-container">
        <div class="row clearfix">

            <!-- Tab Column -->
            <div class="faq-one_title-column col-lg-5 col-md-12 col-sm-12">
                <div class="faq-one_title-outer">
                    <!-- Sec Title -->
                    <div class="sec-title title-anim">
                        <div class="sec-title_title">faq</div>
                        <h2 class="sec-title_heading">Frequently asked <span>questions</span></h2>
                        <div class="sec-title_text">Lorem ipsum dolor sit amet consectetur adipiscing vitae
                            mattis tellus. Nullam quis mattis ligula consectetur.</div>
                    </div>
                    <div class="faq-one_button">
                        <a href="contact.html" class="template-btn btn-style-one">
                            <span class="btn-wrap">
                                <span class="text-one">Contact now</span>
                                <span class="text-two">Contact now</span>
                            </span>
                        </a>
                    </div>
                </div>
            </div>

            <!-- Accordian Column -->
            <div class="faq-one_accordian-column col-lg-7 col-md-12 col-sm-12">
                <div class="faq-one_accordian-outer">

                    <!-- Accordion Box -->
                    <ul class="accordion-box_two">

                        <!-- Block -->
                        <li class="accordion block">
                            <div class="acc-btn">
                                <div class="icon-outer"><span class="icon icon-plus fa-solid fa-plus fa-fw"></span>
                                </div>How does
                                your AI copywriting tool work?
                            </div>
                            <div class="acc-content">
                                <div class="content">
                                    <div class="text">Our AI copywriting tool uses sophisticated algorithms
                                        to understand context, tone, and language nuances. Users input specific
                                        details or prompts, and the AI generates high-quality content based on
                                        that input, refining.</div>
                                </div>
                            </div>
                        </li>

                        <!-- Block -->
                        <li class="accordion block">
                            <div class="acc-btn">
                                <div class="icon-outer"><span class="icon icon-plus fa-solid fa-plus fa-fw"></span>
                                </div>What is AI
                                copywriting?
                            </div>
                            <div class="acc-content">
                                <div class="content">
                                    <div class="text">Our AI copywriting tool uses sophisticated algorithms
                                        to understand context, tone, and language nuances. Users input specific
                                        details or prompts, and the AI generates high-quality content based on
                                        that input, refining.</div>
                                </div>
                            </div>
                        </li>

                        <!-- Block -->
                        <li class="accordion block">
                            <div class="acc-btn">
                                <div class="icon-outer"><span class="icon icon-plus fa-solid fa-plus fa-fw"></span>
                                </div>Can I trust
                                the content generated by AI?
                            </div>
                            <div class="acc-content">
                                <div class="content">
                                    <div class="text">Our AI copywriting tool uses sophisticated algorithms
                                        to understand context, tone, and language nuances. Users input specific
                                        details or prompts, and the AI generates high-quality content based on
                                        that input, refining.</div>
                                </div>
                            </div>
                        </li>

                        <!-- Block -->
                        <li class="accordion block">
                            <div class="acc-btn">
                                <div class="icon-outer"><span class="icon icon-plus fa-solid fa-plus fa-fw"></span>
                                </div>What types
                                of content can your AI generate?
                            </div>
                            <div class="acc-content">
                                <div class="content">
                                    <div class="text">Our AI copywriting tool uses sophisticated algorithms
                                        to understand context, tone, and language nuances. Users input specific
                                        details or prompts, and the AI generates high-quality content based on
                                        that input, refining.</div>
                                </div>
                            </div>
                        </li>

                        <!-- Block -->
                        <li class="accordion block">
                            <div class="acc-btn">
                                <div class="icon-outer"><span class="icon icon-plus fa-solid fa-plus fa-fw"></span>
                                </div>What
                                languages does your AI support?
                            </div>
                            <div class="acc-content">
                                <div class="content">
                                    <div class="text">Our AI copywriting tool uses sophisticated algorithms
                                        to understand context, tone, and language nuances. Users input specific
                                        details or prompts, and the AI generates high-quality content based on
                                        that input, refining.</div>
                                </div>
                            </div>
                        </li>

                    </ul>

                </div>
            </div>

        </div>
    </div>
</section>
